apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    component: web
spec:
      containers:
      - name: nginx
        image: kamendev/simplev2:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: apache-vol
        - mountPath: /var/www
          name: apache-vol
      volumes:
      - name: apache-vol
        persistentVolumeClaim:
          claimName: apache-vol
  volumeClaimTemplates:
  - metadata:
      name: apache-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
