apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  serviceName: nginx-server
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - env:
        - name: nginx_SERVERS
          value: "1"
        image: kamendev/simplev2:latest
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "infinity"
        name: nginx
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: apache-vol
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: apache-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
