apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: kamendev/simplev2:latest
        name: apache
      serviceAccountName: pvc-protection-controller
