apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apache2
spec:
  selector:
    matchLabels:
      app: apache2
  replicas: 1
  serviceName: apache2-server
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - env:
        - name: apache2_SERVERS
          value: "1"
        image: "ubuntu:18.04"
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "infinity"
        name: apache2
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: apache-vol
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: apache-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
